config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :store_flavors
  resources :flavors
  resources :jobs
  resources :shift_jobs
  resources :shifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :stores
  resources :employees
  resources :assignments
  resources :demos, only: [:new, :create, :destroy]
  get 'login', to: 'demos#new', as: :login
  get 'logout', to: 'demos#destroy', as: :logout
  # need routes for authors and categories ...
  
  
  # Set the root url
  root to: 'home#home', as: :home
  get 'active', to: 'stores#active', as: :active_stores
  get 'inactive', to: 'stores#inactive', as: :inactive_stores
  get 'store_manager', to: 'stores#store_manager', as: :store_managers  
  get "active_employees", to: "employees#active_employees", as: :active_employees
  get "inactive_employees", to: "employees#inactive_employees", as: :inactive_employees
  get "younger", to: "employees#younger_than_18", as: :younger_than_18
  get "older", to: "employees#is_18_or_older", as: :is_18_or_older
  get "regulars", to: "employees#regulars", as: :regulars
  get "managers", to: "employees#managers", as: :managers
  get "admins", to: "employees#admins", as: :admins
  get 'current', to: 'assignments#current', as: :current
  get 'past', to: 'assignments#past', as: :past
  get "by_employee", to:"assignments#by_employee", as: :by_employee
  get "chronological", to:"assignments#chronological", as: :chronological
  get "for_store", to:"assignments#for_store", as: :for_store
  get "for_employee", to:"assignments#for_employee", as: :for_employee
  get "for_pay_level", to:"assignments#for_pay_level", as: :for_pay_level
  get "for_role", to:"assignments#for_role", as: :for_role
  get "job_manager", to:"jobs#job_manager", as: :job_manager
  get "flavor_manager", to:"flavors#flavor_manager", as: :flavor_manager
  get "assignment_manager", to:"assignments#assignment_manager", as: :assignment_manager
  get "employee_manager", to:"employees#employee_manager", as: :employee_manager
  get "shift_manager", to:"shifts#shift_manager", as: :shift_manager
  get "add_shift_manager", to:"shifts#add_shift_manager", as: :add_shift_manager
end

app/models/employee.rb
class Employee < ApplicationRecord
 # Callbacks
  before_save :reformat_phone
  before_validation :reformat_ssn
  before_destroy :stop
  after_rollback :make_inactive
  
  
  # Relationships
  has_many :assignments
  has_many :stores, through: :assignments
  has_one :user
  has_many :shifts, through: :assignments
  
    accepts_nested_attributes_for :user
  
  # Validations
  validates_presence_of :first_name, :last_name, :date_of_birth, :ssn, :role
  validates_date :date_of_birth, on_or_before: lambda { 14.years.ago }, on_or_before_message: "must be at least 14 years old"
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only", allow_blank: true
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: "should be 9 digits and delimited with dashes only"
  validates_inclusion_of :role, in: %w[admin manager employee], message: "is not an option"
  validates_uniqueness_of :ssn
  
  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :active,          -> { where(active: true) }
  scope :inactive,        -> { where(active: false) }
  scope :regulars,        -> { where(role: 'employee') }
  scope :managers,        -> { where(role: 'manager') }
  scope :admins,          -> { where(role: 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }
  
  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end
  
  def current_assignment
    curr_assignment = self.assignments.select{|a| a.end_date.nil?}
    # alternative method for finding current assignment is to use scope 'current' in assignments:
    # curr_assignment = self.assignments.current    # will also return an array of current assignments
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end
  
  def over_18?
    date_of_birth < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end
  
  # Misc Constants
  ROLES_LIST = [['Employee', 'employee'],['Manager', 'manager'],['Administrator', 'admin']]
  
  
  # Callback code  (NOT DRY!!!)
  # -----------------------------
  private
   def reformat_phone
     phone = self.phone.to_s  # change to string in case input as all numbers 
     phone.gsub!(/[^0-9]/,"") # strip all non-digits
     self.phone = phone       # reset self.phone to new string
   end
   def reformat_ssn
     ssn = self.ssn.to_s      # change to string in case input as all numbers 
     ssn.gsub!(/[^0-9]/,"")   # strip all non-digits
     self.ssn = ssn           # reset self.ssn to new string
   end
   
    def stop
        throw :abort
    end
    
    def make_inactive
        self.update_attribute(:active, false)
    end
  
  # def clean_up_assignment_and_shifts
  #   if @destroyable
  #     remove_upcoming_shifts
  #     self.current_assignment.delete unless self.current_assignment.nil?
  #   end
  #   @destroyable = nil
  # end
  
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
        
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
  

  def index
     @employees = Employee.alphabetical
  end

  def show
  end

  def new
    @employee = Employee.new
    @employee.build_user
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employee_path(@employee), notice: "#{@employee.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to employee_path(@employee), notice: "#{@employee.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @employee.destroy
    redirect_to employee_url
  end
  
  def active_employees
    @active_employees = Employee.active.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def inactive_employees
    @inactive_employees = Employee.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def younger_than_18
    @younger_than_18 = Employee.younger_than_18.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def is_18_or_older
    @is_18_or_older = Employee.is_18_or_older.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def regulars
    @regulars = Employee.regulars.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def managers
    @managers = Employee.managers.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def admins
    @admins = Employee.admins.alphabetical.paginate(page: params[:page]).per_page(10)
  end
    
  def employee_manager
    @employee_manager = Employee.alphabetical
  end
  
    

  private
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :ssn, :date_of_birth, :phone, :role, :active,  user_attributes: [:id, :email, :password, :_destroy])
  end
  
  def set_employee
    @employee = Employee.find(params[:id])
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>

<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :ssn %>
    <%= form.text_field :ssn %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth, prompt: "Date of Birth", class: "datepicker", :value =>
					(form.object.date_of_birth.strftime('%B %d, %Y') if form.object.date_of_birth != nil)%>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.select :role, options_for_select([['Employee', 'employee'],['Manager', 'manager'],['Administrator', 'admin']]), :prompt => 'Select Role'%>
  </div>

  <div class="field">
    <%= form.label :active %><br />
    <%= form.select :active, options_for_select([['Yes', true], ['No', false]])%>
  </div>
  <div class="field">
  <%= form.fields_for :user do |f| %>
    <%= f.label "Email" %>
    <%= f.email_field :email %>
    
    <%= f.label "Password" %>
    <%= f.password_field :password %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn btn-outline-secondary" %>
    <%= link_to 'Cancel', stores_path, :class => "btn btn-outline-secondary" %>
  </div>
    <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

<% end %>

app/views/employees/active_employees.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Active Employees</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/admins.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of all admins</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/employee_manager.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Employees</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_manager.each do |employee| %>
       <% if current_user_store.id == Assignment.find(employee.id).store_id %> 
      <tr>
        <td> <%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
      </tr>
        <% end %>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/inactive_employees.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Active Employees</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inactive_employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/index.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Employees</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/is_18_or_older.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Active Employees</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @is_18_or_older.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/managers.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List all mangers</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/new.html.erb
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<div class="container">
<h1>New Employees</h1>
</div>
<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/regulars.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of all Employees</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regulars.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @employee.ssn %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @employee.date_of_birth %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Role:</strong>
  <%= @employee.role %>
</p>

<p>
  <strong>Active:</strong>
  <%= @employee.active %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/younger_than_18.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Active Employees</h1>

<%= link_to 'New Employee', new_employee_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Snn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @younger_than_18.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>