config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :store_flavors
  resources :flavors
  resources :jobs
  resources :shift_jobs
  resources :shifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :stores
  resources :employees
  resources :assignments
  resources :demos, only: [:new, :create, :destroy]
  get 'login', to: 'demos#new', as: :login
  get 'logout', to: 'demos#destroy', as: :logout
  # need routes for authors and categories ...
  
  
  # Set the root url
  root to: 'home#home', as: :home
  get 'active', to: 'stores#active', as: :active_stores
  get 'inactive', to: 'stores#inactive', as: :inactive_stores
  get 'store_manager', to: 'stores#store_manager', as: :store_managers  
  get "active_employees", to: "employees#active_employees", as: :active_employees
  get "inactive_employees", to: "employees#inactive_employees", as: :inactive_employees
  get "younger", to: "employees#younger_than_18", as: :younger_than_18
  get "older", to: "employees#is_18_or_older", as: :is_18_or_older
  get "regulars", to: "employees#regulars", as: :regulars
  get "managers", to: "employees#managers", as: :managers
  get "admins", to: "employees#admins", as: :admins
  get 'current', to: 'assignments#current', as: :current
  get 'past', to: 'assignments#past', as: :past
  get "by_employee", to:"assignments#by_employee", as: :by_employee
  get "chronological", to:"assignments#chronological", as: :chronological
  get "for_store", to:"assignments#for_store", as: :for_store
  get "for_employee", to:"assignments#for_employee", as: :for_employee
  get "for_pay_level", to:"assignments#for_pay_level", as: :for_pay_level
  get "for_role", to:"assignments#for_role", as: :for_role
  get "job_manager", to:"jobs#job_manager", as: :job_manager
  get "flavor_manager", to:"flavors#flavor_manager", as: :flavor_manager
  get "assignment_manager", to:"assignments#assignment_manager", as: :assignment_manager
  get "employee_manager", to:"employees#employee_manager", as: :employee_manager
  get "shift_manager", to:"shifts#shift_manager", as: :shift_manager
  get "add_shift_manager", to:"shifts#add_shift_manager", as: :add_shift_manager
end

app/models/assignment.rb
class Assignment < ApplicationRecord
# Callbacks
  before_create :end_previous_assignment
  before_destroy :destroyable?
  after_rollback :terminate_assignment
  
  # Relationships
  belongs_to :employee
  belongs_to :store
  has_many :shifts
  
  # Validations
  validates_numericality_of :pay_level, only_integer: true, greater_than: 0, less_than: 7
  validates_date :start_date, on_or_before: lambda { Date.current }, on_or_before_message: "cannot be in the future"
  validates_date :end_date, after: :start_date, on_or_before: lambda { Date.current }, allow_blank: true
  validate :employee_is_active_in_system, on: :create
  validate :store_is_active_in_system, on: :create
  validates_presence_of :employee_id, on: :update
  validates_presence_of :store_id, on: :update
  
  # Scopes
  scope :current,       -> { where(end_date: nil) }
  scope :past,          -> { where.not(end_date: nil) }
  scope :by_store,      -> { joins(:store).order('name') }
  scope :by_employee,   -> { joins(:employee).order('last_name, first_name') }
  scope :chronological, -> { order('start_date DESC, end_date DESC') }
  scope :for_store,     ->(store_id) { where("store_id = ?", store_id) }
  scope :for_employee,  ->(employee_id) { where("employee_id = ?", employee_id) }
  scope :for_pay_level, ->(pay_level) { where("pay_level = ?", pay_level) }
  scope :for_role,      ->(role) { joins(:employee).where("role = ?", role) }


  def destroyable?
    @destroyable = self.shifts.past.empty?
  end
  
  def terminate_assignment
    remove_future_shifts if @destroyable == false
    self.update_attribute(:end_date, Date.current) if @destroyable == false
    return "Removed successfully"
  end
  
  def remove_future_shifts
    @future_shifts = self.shifts.upcoming
    @future_shifts.each {|s| s.destroy}
  end
  
  # Private methods for callbacks and custom validations
  private  
  
  def end_previous_assignment
    current_assignment = Employee.find(self.employee_id).current_assignment
    if current_assignment.nil?
      return true 
    else
      current_assignment.update_attribute(:end_date, self.start_date.to_date)
    end
  end
  
  # Again, these are not DRY
  def employee_is_active_in_system
    all_active_employees = Employee.active.all.map{|e| e.id}
    unless all_active_employees.include?(self.employee_id)
      errors.add(:employee_id, "is not an active employee at the creamery")
    end
  end
  
  def store_is_active_in_system
    all_active_stores = Store.active.all.map{|s| s.id}
    unless all_active_stores.include?(self.store_id)
      errors.add(:store_id, "is not an active store at the creamery")
    end
  end
    

  
  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
        
  before_action :set_assignment, only: [:show,:edit, :update, :destroy]


  def index
    @assignments = Assignment.chronological
  end

   def show
   end

  def new
    @assignment = Assignment.new
  end

  def edit
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to @assignment, notice: "#{@assignment.employee.proper_name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @assignment.update(assignment_params)
      redirect_to @assignment, notice: "#{@assignment.employee.proper_name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @assignment.destroy
    redirect_to assignments_url
  end
  
  def current
    @current = Assignment.current.paginate(page: params[:page]).per_page(10)
  end
    
  def past
    @past = Assignment.past.paginate(page: params[:page]).per_page(10)
  end
  
  def by_employee
    @by_employee = Assignment.by_employee.paginate(page: params[:page]).per_page(10)
  end
  
  def chronological
    @chronological = Assignment.chronological.paginate(page: params[:page]).per_page(10)
  end
  
  def for_store
    @for_store = Assignment.for_store(1)
  end
  
  def for_employee
    @for_employee = Assignment.for_employee(1)
  end
  
  def for_pay_level
    @for_pay_level = Assignment.for_pay_level(1)
  end
  
  def for_role
    @for_role = Assignment.for_role("admin")
  end
  
  def assignment_manager
    @assignment_manager = Assignment.by_store.paginate(page: params[:page]).per_page(15)
  end
  
  
  
  
  
  
  

  private
  
  def assignment_params
    params.require(:assignment).permit(:employee_id, :store_id, :start_date, :end_date, :pay_level)
  end
  
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end



end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<%= form_with(model: assignment, local: true) do |form| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="field">
    <%= form.label :store_id %>
    <%= form.collection_select :store_id, Store.active.alphabetical, :id, :name, :prompt => "Select ..." %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.collection_select :employee_id, Employee.active.alphabetical, :id, :name, :prompt => "Select ..." %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
					<%= form.text_field :start_date, prompt: "Start Date", class: "datepicker", :value =>
					(form.object.start_date.strftime('%B %d, %Y') if form.object.start_date != nil)%>
  </div>

  <div class="field">
    <%= form.label :end_date %>
					<%= form.text_field :end_date, prompt: "End Date", class: "datepicker", :value =>
					(form.object.end_date.strftime('%B %d, %Y') if form.object.end_date != nil)%>
  </div>

  <div class="field">
    <%= form.label :pay_level %>
    <%= form.number_field :pay_level %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn waves-effect waves-light" %>
    <%= link_to 'Cancel', stores_path, :class => 'waves-effect waves-light btn red' %>
  </div>
    <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>
<% end %>

app/views/assignments/assignment_manager.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Assignments</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignment_manager.each do |assignment| %>
      <% if current_user_store.name == Store.find( assignment.store_id).name %>
      <tr>
        <td><%= Store.find( assignment.store_id).name %></td>
        <td><%= Employee.find( assignment.employee_id).name %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/assignments/by_employee.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Assignments By Employees</h1>

<%= link_to 'New Assignment', new_assignment_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @by_employee.each do |assignment| %>
      <tr>
        <td><%= Store.find( assignment.store_id).name %></td>
        <td><%= Employee.find( assignment.employee_id).name %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/assignments/chronological.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Assignments</h1>

<%= link_to 'New Assignment', new_assignment_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chronological.each do |assignment| %>
      <tr>
        <td><%= Store.find( assignment.store_id).name %></td>
        <td><%= Employee.find( assignment.employee_id).name %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/assignments/current.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Assignments</h1>

<%= link_to 'New Assignment', new_assignment_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @current.each do |assignment| %>
      <tr>
        <td><%= Store.find( assignment.store_id).name %></td>
        <td><%= Employee.find( assignment.employee_id).name %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/for_store.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Assignments</h1>

<%= link_to 'New Assignment', new_assignment_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @for_store.each do |assignment| %>
      <tr>
        <td><%= Store.find( assignment.store_id).name %></td>
        <td><%= Employee.find( assignment.employee_id).name %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/assignments/index.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Assignments</h1>

<%= link_to 'New Assignment', new_assignment_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= Store.find( assignment.store_id).name %></td>
        <td><%= Employee.find( assignment.employee_id).name %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/assignments/new.html.erb
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<div class="container">
<h1>New Assignments</h1>
</div>
<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/past.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Assignments</h1>

<%= link_to 'New Assignment', new_assignment_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @past.each do |assignment| %>
      <tr>
        <td><%= Store.find( assignment.store_id).name %></td>
        <td><%= Employee.find( assignment.employee_id).name %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= Store.find(@assignment.store_id).name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= Employee.find(@assignment.employee_id).name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @assignment.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @assignment.end_date %>
</p>

<p>
  <strong>Pay level:</strong>
  <%= @assignment.pay_level %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>