config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :store_flavors
  resources :flavors
  resources :jobs
  resources :shift_jobs
  resources :shifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :stores
  resources :employees
  resources :assignments
  resources :demos, only: [:new, :create, :destroy]
  get 'login', to: 'demos#new', as: :login
  get 'logout', to: 'demos#destroy', as: :logout
  # need routes for authors and categories ...
  
  
  # Set the root url
  root to: 'home#home', as: :home
  get 'active', to: 'stores#active', as: :active_stores
  get 'inactive', to: 'stores#inactive', as: :inactive_stores
  get 'store_manager', to: 'stores#store_manager', as: :store_managers  
  get "active_employees", to: "employees#active_employees", as: :active_employees
  get "inactive_employees", to: "employees#inactive_employees", as: :inactive_employees
  get "younger", to: "employees#younger_than_18", as: :younger_than_18
  get "older", to: "employees#is_18_or_older", as: :is_18_or_older
  get "regulars", to: "employees#regulars", as: :regulars
  get "managers", to: "employees#managers", as: :managers
  get "admins", to: "employees#admins", as: :admins
  get 'current', to: 'assignments#current', as: :current
  get 'past', to: 'assignments#past', as: :past
  get "by_employee", to:"assignments#by_employee", as: :by_employee
  get "chronological", to:"assignments#chronological", as: :chronological
  get "for_store", to:"assignments#for_store", as: :for_store
  get "for_employee", to:"assignments#for_employee", as: :for_employee
  get "for_pay_level", to:"assignments#for_pay_level", as: :for_pay_level
  get "for_role", to:"assignments#for_role", as: :for_role
  get "job_manager", to:"jobs#job_manager", as: :job_manager
  get "flavor_manager", to:"flavors#flavor_manager", as: :flavor_manager
  get "assignment_manager", to:"assignments#assignment_manager", as: :assignment_manager
  get "employee_manager", to:"employees#employee_manager", as: :employee_manager
  get "shift_manager", to:"shifts#shift_manager", as: :shift_manager
  get "add_shift_manager", to:"shifts#add_shift_manager", as: :add_shift_manager
end

app/models/flavor.rb
class Flavor < ApplicationRecord
    
  has_many :store_flavors
  has_many :stores, through: :store_flavors
  
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :alphabetical, -> { order(:name) }
  
  validates_presence_of :name
  
  before_destroy :stop
  after_rollback :make_inactive
     
  private
    def stop
        throw :abort
    end
    
    def make_inactive
        self.update_attribute(:active, false)
    end

  
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor.destroy
    respond_to do |format|
      format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def flavor_manager
    @flavor_manager = Flavor.alphabetical.paginate(page: params[:page]).per_page(10) 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name, :active)
    end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>

<%= form_with(model: flavor, local: true) do |form| %>
  <% if flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flavor.errors.count, "error") %> prohibited this flavor from being saved:</h2>

      <ul>
      <% flavor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :active %><br />
    <%= form.select :active, options_for_select([['Yes', true], ['No', false]])%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flavors/edit.html.erb
<h1>Editing Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Show', @flavor %> |
<%= link_to 'Back', flavors_path %>

app/views/flavors/flavor_manager.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Flavors</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flavor_manager.each do |flavor| %>
      <tr>
        <td><%= flavor.name %></td>
        <td><%= flavor.active %></td>
        <td><%= link_to 'Show', flavor %></td>

      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/flavors/index.html.erb
  <style>
    body { background-color: #FFCFCA; }
  </style>
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
<h1>List of Flavors</h1>

<%= link_to 'New Flavor', new_flavor_path, :class=> "right" %><br>
<table class="striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flavors.each do |flavor| %>
      <tr>
        <td><%= flavor.name %></td>
        <td><%= flavor.active %></td>
        <td><%= link_to 'Show', flavor %></td>
        <td><%= link_to 'Edit', edit_flavor_path(flavor) %></td>
        <td><%= link_to 'Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <div class="small-1 columns">&nbsp;</div>
	<div class="small-5 columns">&nbsp;</div>
</div>

app/views/flavors/new.html.erb
<h1>New Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Back', flavors_path %>

app/views/flavors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flavor.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @flavor.active %>
</p>

<%= link_to 'Edit', edit_flavor_path(@flavor) %> |
<%= link_to 'Back', flavors_path %>